repository = "https://github.com/DRAGGON-Lab/SBOLInventory"
revision = "e992f18494c2a363ee9675ac8e12ca37ecc4538a"
profile = "https://sbol.io/spec/sbol-inventory/0.2"
status = "draft"
vendored_at = "2026-09-08"
