repository = "https://github.com/DRAGGON-Lab/SBOLInventory"
revision = "7d8cb750dd2d5e3c6c7602e575c3a551b890724f"
profile = "https://sbol.io/spec/sbol-inventory/0.2"
status = "draft"
vendored_at = "2026-08-28"
