repository = "https://github.com/DRAGGON-Lab/SBOLInventory"
revision = "b5066f86869655ab9aae4da172db272fbb109dca"
profile = "https://sbol.io/spec/sbol-inventory/0.2"
status = "draft"
vendored_at = "2026-09-08"
